/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CartItems".
 */
export type CartItems =
	| {
			variant?: (number | null) | ProductVariant;
			quantity?: number | null;
			isSelected?: boolean | null;
			id?: string | null;
	  }[]
	| null;

export interface Config {
	collections: {
		// pages: Page;
		products: Product;
		"product-variations": ProductVariant;
		orders: Order;
		media: Media;
		categories: Category;
		users: User;
		subscribers: Subscriber;
		"support-tickets": SupportTicket;
		redirects: Redirect;
	};
	globals: {
		settings: Settings;
		header: Header;
		footer: Footer;
	};
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
// export interface Page {
// 	id: number;
// 	title: string;
// 	publishedOn?: string | null;
// 	hero: {
// 		type: "none" | "highImpact" | "mediumImpact" | "lowImpact" | "mainImpact";
// 		richText: {
// 			[k: string]: unknown;
// 		}[];
// 		links?:
// 			| {
// 					link: {
// 						type?: ("reference" | "custom") | null;
// 						newTab?: boolean | null;
// 						reference?: {
// 							relationTo: "pages";
// 							value: number | Page;
// 						} | null;
// 						url?: string | null;
// 						label: string;
// 						appearance?: ("default" | "primary" | "secondary") | null;
// 					};
// 					id?: string | null;
// 			  }[]
// 			| null;
// 		media?: number | Media | null;
// 	};
// 	layout: (
// 		| {
// 				invertBackground?: boolean | null;
// 				richText: {
// 					[k: string]: unknown;
// 				}[];
// 				links?:
// 					| {
// 							link: {
// 								type?: ("reference" | "custom") | null;
// 								newTab?: boolean | null;
// 								reference?: {
// 									relationTo: "pages";
// 									value: number | Page;
// 								} | null;
// 								url?: string | null;
// 								label: string;
// 								appearance?: ("primary" | "secondary") | null;
// 							};
// 							id?: string | null;
// 					  }[]
// 					| null;
// 				id?: string | null;
// 				blockName?: string | null;
// 				blockType: "cta";
// 		  }
// 		| {
// 				invertBackground?: boolean | null;
// 				isTabs?: boolean | null;
// 				columns?:
// 					| {
// 							title?:
// 								| {
// 										[k: string]: unknown;
// 								  }[]
// 								| null;
// 							size?: ("oneThird" | "half" | "twoThirds" | "full") | null;
// 							richText: {
// 								[k: string]: unknown;
// 							}[];
// 							enableLink?: boolean | null;
// 							link?: {
// 								type?: ("reference" | "custom") | null;
// 								newTab?: boolean | null;
// 								reference?: {
// 									relationTo: "pages";
// 									value: number | Page;
// 								} | null;
// 								url?: string | null;
// 								label: string;
// 								appearance?: ("default" | "primary" | "secondary") | null;
// 							};
// 							id?: string | null;
// 					  }[]
// 					| null;
// 				id?: string | null;
// 				blockName?: string | null;
// 				blockType: "content";
// 		  }
// 		| {
// 				invertBackground?: boolean | null;
// 				position?: ("default" | "fullscreen") | null;
// 				media: number | Media;
// 				id?: string | null;
// 				blockName?: string | null;
// 				blockType: "mediaBlock";
// 		  }
// 		| {
// 				introContent: {
// 					[k: string]: unknown;
// 				}[];
// 				populateBy?: ("collection" | "selection") | null;
// 				slider?: boolean | null;
// 				moreLink: {
// 					type?: ("reference" | "custom") | null;
// 					newTab?: boolean | null;
// 					reference?: {
// 						relationTo: "pages";
// 						value: number | Page;
// 					} | null;
// 					url?: string | null;
// 					label: string;
// 					appearance?: ("default" | "primary" | "secondary") | null;
// 				};
// 				relationTo?: "products" | null;
// 				categories?: (number | Category)[] | null;
// 				limit?: number | null;
// 				selectedDocs?:
// 					| {
// 							relationTo: "products";
// 							value: number | Product;
// 					  }[]
// 					| null;
// 				populatedDocs?:
// 					| {
// 							relationTo: "products";
// 							value: number | Product;
// 					  }[]
// 					| null;
// 				populatedDocsTotal?: number | null;
// 				id?: string | null;
// 				blockName?: string | null;
// 				blockType: "archive";
// 		  }
// 		| {
// 				introContent: {
// 					[k: string]: unknown;
// 				}[];
// 				mediaBackground: number | Media;
// 				mediaForeground?: number | Media | null;
// 				contentTitle: {
// 					[k: string]: unknown;
// 				}[];
// 				contentBody?:
// 					| {
// 							[k: string]: unknown;
// 					  }[]
// 					| null;
// 				id?: string | null;
// 				blockName?: string | null;
// 				blockType: "workflow";
// 		  }
// 		| {
// 				introContent: {
// 					[k: string]: unknown;
// 				}[];
// 				cards?:
// 					| {
// 							title: string;
// 							description: {
// 								[k: string]: unknown;
// 							}[];
// 							image: number | Media;
// 							id?: string | null;
// 					  }[]
// 					| null;
// 				profits?:
// 					| {
// 							title: string;
// 							id?: string | null;
// 					  }[]
// 					| null;
// 				marquee?:
// 					| {
// 							title: string;
// 							id?: string | null;
// 					  }[]
// 					| null;
// 				id?: string | null;
// 				blockName?: string | null;
// 				blockType: "advantages";
// 		  }
// 		| {
// 				introContent: {
// 					[k: string]: unknown;
// 				}[];
// 				description: {
// 					[k: string]: unknown;
// 				}[];
// 				cards?:
// 					| {
// 							enableLink?: boolean | null;
// 							media: number | Media;
// 							link?: {
// 								type?: ("reference" | "custom") | null;
// 								newTab?: boolean | null;
// 								reference?: {
// 									relationTo: "pages";
// 									value: number | Page;
// 								} | null;
// 								url?: string | null;
// 								label: string;
// 								appearance?: ("default" | "primary" | "secondary") | null;
// 							};
// 							id?: string | null;
// 					  }[]
// 					| null;
// 				id?: string | null;
// 				blockName?: string | null;
// 				blockType: "besides";
// 		  }
// 	)[];
// 	slug?: string | null;
// 	meta?: {
// 		title?: string | null;
// 		description?: string | null;
// 		image?: number | Media | null;
// 	};
// 	updatedAt: string;
// 	createdAt: string;
// 	_status?: ("draft" | "published") | null;
// }
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
	id: number;
	alt: string;
	caption?:
		| {
				[k: string]: unknown;
		  }[]
		| null;
	updatedAt: string;
	createdAt: string;
	url?: string | null;
	filename?: string | null;
	mimeType?: string | null;
	filesize?: number | null;
	width?: number | null;
	height?: number | null;
	focalX?: number | null;
	focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
	id: number;
	title?: string | null;
	parent?: (number | null) | Category;
	breadcrumbs?:
		| {
				doc?: (number | null) | Category;
				url?: string | null;
				label?: string | null;
				id?: string | null;
		  }[]
		| null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
	id: number;
	title: string;
	publishedOn?: string | null;
	// layout: (
	// 	| {
	// 			invertBackground?: boolean | null;
	// 			richText: {
	// 				[k: string]: unknown;
	// 			}[];
	// 			links?:
	// 				| {
	// 						link: {
	// 							type?: ("reference" | "custom") | null;
	// 							newTab?: boolean | null;
	// 							reference?: {
	// 								relationTo: "pages";
	// 								value: number | Page;
	// 							} | null;
	// 							url?: string | null;
	// 							label: string;
	// 							appearance?: ("primary" | "secondary") | null;
	// 						};
	// 						id?: string | null;
	// 				  }[]
	// 				| null;
	// 			id?: string | null;
	// 			blockName?: string | null;
	// 			blockType: "cta";
	// 	  }
	// 	| {
	// 			invertBackground?: boolean | null;
	// 			isTabs?: boolean | null;
	// 			columns?:
	// 				| {
	// 						title?:
	// 							| {
	// 									[k: string]: unknown;
	// 							  }[]
	// 							| null;
	// 						size?: ("oneThird" | "half" | "twoThirds" | "full") | null;
	// 						richText: {
	// 							[k: string]: unknown;
	// 						}[];
	// 						enableLink?: boolean | null;
	// 						link?: {
	// 							type?: ("reference" | "custom") | null;
	// 							newTab?: boolean | null;
	// 							reference?: {
	// 								relationTo: "pages";
	// 								value: number | Page;
	// 							} | null;
	// 							url?: string | null;
	// 							label: string;
	// 							appearance?: ("default" | "primary" | "secondary") | null;
	// 						};
	// 						id?: string | null;
	// 				  }[]
	// 				| null;
	// 			id?: string | null;
	// 			blockName?: string | null;
	// 			blockType: "content";
	// 	  }
	// 	| {
	// 			invertBackground?: boolean | null;
	// 			position?: ("default" | "fullscreen") | null;
	// 			media: number | Media;
	// 			id?: string | null;
	// 			blockName?: string | null;
	// 			blockType: "mediaBlock";
	// 	  }
	// 	| {
	// 			introContent: {
	// 				[k: string]: unknown;
	// 			}[];
	// 			populateBy?: ("collection" | "selection") | null;
	// 			slider?: boolean | null;
	// 			moreLink: {
	// 				type?: ("reference" | "custom") | null;
	// 				newTab?: boolean | null;
	// 				reference?: {
	// 					relationTo: "pages";
	// 					value: number | Page;
	// 				} | null;
	// 				url?: string | null;
	// 				label: string;
	// 				appearance?: ("default" | "primary" | "secondary") | null;
	// 			};
	// 			relationTo?: "products" | null;
	// 			categories?: (number | Category)[] | null;
	// 			limit?: number | null;
	// 			selectedDocs?:
	// 				| {
	// 						relationTo: "products";
	// 						value: number | Product;
	// 				  }[]
	// 				| null;
	// 			populatedDocs?:
	// 				| {
	// 						relationTo: "products";
	// 						value: number | Product;
	// 				  }[]
	// 				| null;
	// 			populatedDocsTotal?: number | null;
	// 			id?: string | null;
	// 			blockName?: string | null;
	// 			blockType: "archive";
	// 	  }
	// )[];
	stripeProductID?: string | null;
	priceJSON?: string | null;

	variations?: (number | ProductVariant)[] | null;
	categories?: (number | Category)[] | null;
	relatedProducts?: (number | Product)[] | null;
	slug?: string | null;
	skipSync?: boolean | null;
	meta?: {
		title?: string | null;
		description?: string | null;
		image?: number | Media | null;
	};
	updatedAt: string;
	createdAt: string;
	_status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-variants".
 */
export interface ProductVariant {
	id: number;
	sizeName: string;
	sizeUnit: number;
	sizeDescription: string;
	images?:
		| {
				image: number | Media;
				id?: string | null;
		  }[]
		| null;
	stripePriceId: string;
	stripePriceUnitAmount?: number | null;
	product: number | Product;
	stock?: number | null;
	updatedAt: string;
	createdAt: string;
	_status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
	id: number;
	orderedBy?: (number | null) | User;
	status?: ("pending" | "completed" | "cancelled") | null;
	stripePaymentIntentID?: string | null;
	total: number;
	items?:
		| {
				variant: number | ProductVariant;
				price?: number | null;
				quantity?: number | null;
				isSelected?: boolean | null;
				id?: string | null;
		  }[]
		| null;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
	id: number;
	name?: string | null;
	roles?: ("admin" | "customer")[] | null;
	purchases?: (number | ProductVariant)[] | null;
	stripeCustomerID?: string | null;
	cart?: {
		items?: CartItems;
	};
	skipSync?: boolean | null;
	updatedAt: string;
	createdAt: string;
	email: string;
	resetPasswordToken?: string | null;
	resetPasswordExpiration?: string | null;
	salt?: string | null;
	hash?: string | null;
	_verified?: boolean | null;
	_verificationToken?: string | null;
	loginAttempts?: number | null;
	lockUntil?: string | null;
	password: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
	id: number;
	email: string;
	updatedAt: string;
	createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "support-tickets".
 */
export interface SupportTicket {
	id: number;
	email: string;
	category?: ("bug" | "question" | "feedback") | null;
	subject: string;
	description: string;
	status?: ("open" | "in_progress" | "resolved" | "closed") | null;
	createdAt: string;
	updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
	id: number;
	from: string;
	to?: {
		type?: ("reference" | "custom") | null;
		reference?:
			| ({
					relationTo: "pages";
					value: number;
			  } | null)
			| ({
					relationTo: "products";
					value: number | Product;
			  } | null);
		url?: string | null;
	};
	updatedAt: string;
	createdAt: string;
}

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Settings {
	id: number;
	productsPage?: number | null;
	updatedAt?: string | null;
	createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
	id: number;
	navItems?:
		| {
				link: {
					type?: ("reference" | "custom") | null;
					newTab?: boolean | null;
					reference?: {
						relationTo: "pages";
						value: number;
					} | null;
					url?: string | null;
					label: string;
				};
				id?: string | null;
		  }[]
		| null;
	updatedAt?: string | null;
	createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
	id: number;
	navItems?:
		| {
				link: {
					type?: ("reference" | "custom") | null;
					newTab?: boolean | null;
					reference?: {
						relationTo: "pages";
						value: number;
					} | null;
					url?: string | null;
					label: string;
				};
				id?: string | null;
		  }[]
		| null;
	// columns?:
	// 	| {
	// 			title: string;
	// 			links?:
	// 				| {
	// 						link: {
	// 							type?: ("reference" | "custom") | null;
	// 							newTab?: boolean | null;
	// 							reference?: {
	// 								relationTo: "pages";
	// 								value: number | Page;
	// 							} | null;
	// 							url?: string | null;
	// 							label: string;
	// 							appearance?: ("default" | "primary" | "secondary") | null;
	// 						};
	// 						id?: string | null;
	// 				  }[]
	// 				| null;
	// 			id?: string | null;
	// 	  }[]
	// 	| null;
	updatedAt?: string | null;
	createdAt?: string | null;
}

// declare module "payload" {
// 	export interface GeneratedTypes extends Config {}
// }
